### ISSUE TITLE
コミュニケーションツールについて

### ISSUE THREAD

**Issue by yorreb** [Jmblllllr/core#10]
### ※　2015.3.25現在、主なコミュニケーションはSlack上で行うことになりました。

新規参加　-> https://jmblr-jp-slack.herokuapp.com/
Jmblllllr Slack Group -> https://jmblr-jp.slack.com

**Comment by yorreb** [comment]
@takumi987 

いかがでしょうか。。。？

**Comment by yorreb** [comment]
@takumi987 

このコメントの2つ前に

> yorreb referenced this issue a minute ago
> hangout On Airミーティング以外での意思決定方法を設定 #7

とあるように、issuesで話を展開していくことでリファレンスも自動で取ってくれたりするので、その点でもいいかなと思っているんですが。。

**Comment by yorreb** [comment]
これは「やり取りを公開すべきか公開すべきでないか」という議論なのかもしれませんね。

@takumi987

**Comment by takumi987** [comment]
雑談用issuesの活用は書き込むだけなので、発言やレファレンスもとりやすくコミュニケーションの場としてすごく活用しやすいと思います。プロジェクトの動きや方針を決めていく場としても活用していいのではないかと感じました。このような雑談の場で決め事も行うならはオープンでも大丈夫かなと思います。

**Comment by yorreb** [comment]
@Jmblllllr/issues-contributor 
@takumi987 

> 雑談用issuesの活用は書き込むだけなので、発言やレファレンスもとりやすくコミュニケーションの場としてすごく活用しやすいと思います。プロジェクトの動きや方針を決めていく場としても活用していいのではないかと感じました。

了解しました。！
上の発言を受けて **Team "Issues contributor"** を作ってみました。名の通り、ここをはじめとした各issuesでの発言一つ一つを通して、プロジェクトの動きや方針の決定・改善にご協力いただければ…と思っています。
試行として現在 @takumi987 はそちらのチームに Join していただいています。

ちなみに、teamの権限もこちらで設定してみたのですが、、、もしコメントできなくなった等の不都合あるようでしたら、お手数ですが個人的にご連絡ください。！

またteam名が気に入らない等の意見もあればコメント頂けるとうれしいです。（正直、ネーミングセンスには全く自信がありません…）

**Comment by yorreb** [comment]
@Jmblllllr/issues-contributor 
@Jmblllllr/owners 

動きの流れとしては、、、

まずmdファイルなどを編集できる(ような知識をもっている)人(現段階では @yorreb )が issues contributor ( @Jmblllllr/issues-contributor ) とは別のteamに加っており( 現段階では @Jmblllllr/owners )、
記録としてのファイルを作成・編集しながらこのissues #10 上に、ファイルリンクとともに報告を挙げていきます。

（これは事後報告でも大丈夫です。gitはバージョン管理システムなので、事後報告後に @Jmblllllr/issues-contributor が異議アリとした場合、いつでも作成前・編集前の状態に戻せます。)

(バージョン管理システムってなんだろう。。。？という方は、 [バージョン管理システム - Wikipedia](http://ja.wikipedia.org/wiki/%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E7%AE%A1%E7%90%86%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0) を参照してみてください。！ ）

@Jmblllllr/issues-contributor の人々は、この #10 に挙げられてくる各報告に対して積極的にコメントをいただけるとうれしいです。そのコメントを受けて、改善や方針の決定・変更などを行っていきます。

また @Jmblllllr/issues-contributor 側から提言していただいて 他のteamの方々がその提案に乗ることで動きを作っていってもいいと思います。

いずれにせよ @Jmblllllr/issues-contributor の人々のコメント一つ一つが、このプロジェクトの推進力となります。この Jmblllllr/core issues #10 は、Jmblllllr の全ての動き・方針に関する質問・提案・話し合いの場ですので、遠慮なくご参加・ご意見ください。！

**Comment by takumi987** [comment]
@yorrebさん　お疲れ様です。返信遅くなりました。すみません。

上記の内容の自分への確認として、

Communication Issues  
←全体の動き・方針に関する質問・提案等の話し合いの場であり、@Jmblllllr/issues-contributorまたは  @Jmblllllr/owners の各グループのお互いがコメントできる場
　　　　　
@Jmblllllr/issues-contributor ←プロジェクト参加メンバーが加入しているグループ

 @Jmblllllr/owners ←mdファイルの編集可能で、報告内容が書いてあるファイルリンクをCommunication 　　　　　　　　　　　　　　　　　issuesに投稿（提言は@Jmblllllr/issues-contributor からでも可能）

この仕組みに関して賛成です。運用していって改善点がでてきたらまたその時は話し合っていきましょう。

**Comment by yorreb** [comment]
@takumi987 

お疲れ様です。
ちょっと Jmblllllr プロジェクト内に別リポジトリを建てさせていただきます。
理由は、
1. 現状の Jmblllllr/core の意思決定ルールでは、自分も @takumi987 に合意を得て、且つ記録を残していかなければ(このリポジトリ内での)行動を取ることができない。
2. 合意の意思を示そうにも、、現状のコミュニケーション手段であるGoogle Hangoutやgithubに慣れていないと『意思の示し方』がわからない。示せない。。
3. 結果、オーガナイゼーションメンバーの合意が取れないので、誰も動けない。。

という悪循環が生まれているからです。

なので、運用の仕方の模索も含めて、1度 Jmblllllrプロジェクト内に別リポジトリを設けてそこで色々やってみます。

https://yorreb.wordpress.com/2015/03/01/%e3%82%ac%e3%83%ac%e3%83%bc%e3%82%b8%e3%81%a4%e3%81%8f%e3%81%a3%e3%81%9f%e3%80%82/

**Comment by takumi987** [comment]
お疲れ様です。
メールチェック遅くなりました、すみません。内容確認しました。
招待していただいたJmblllllrzGarageのGitterに参加させていただきましたー。

**Comment by yorreb** [comment]
2015.3.25現在

Jmblllllr 関連のコミュニケーションは [Jmblllllr Slack](https://jmblr-jp.slack.com) にまとめられるようになりました。  
Jmblllllr Slack グループに参加したい場合は、こちらからお願いします。 -> [jmblr-jp-slack](https://jmblr-jp-slack.herokuapp.com/)

故にこのissueはcloseします。
