### ISSUE TITLE
Pull Requestsテスト

### ISSUE THREAD

**Issue by yorreb** [Jmblllllr/core#3]
takumi987 issue test

**Comment by takumi987** [comment]
close 完了

**Comment by yorreb** [comment]
@takumi987 

## Pull Requestsのテスト

現時点 (add CONTRIBUTING.md) でのブランチ「takumi987」を、プルリクエストしてみてください。
どんな些細なことでもいいので、、質問があるようでしたら気軽にここ(Github issuesのコメント欄)やHangout、LINEなどにご連絡ください。

**Comment by yorreb** [comment]
@takumi987 は @Jmblllllr/issues-contributor に join しましたので、この項目はcloseします。
