### ISSUE TITLE
Weekly Update

### ISSUE THREAD

**Issue by yorreb** [Jmblllllr/core#5]
@takumi987 

2015/2/27時点での１週間のまとめをお願いします。weeklyフォルダに前週のウィークリーアップデートがあるので、書き方の参考にしてみてください。

**Comment by yorreb** [comment]
@takumi987 は team @Jmblllllr/issues-contributor に join しましたので、ウィークリーアップデート2015/2/27 は @yorreb が編集します。

**Comment by takumi987** [comment]
@yorrebさん　すみません。
自分もファイル編集が安全に行えるように@takumi987の中でいじって、慣れていきたいです。

**Comment by yorreb** [comment]
@takumi987 

了解です。

ではお手数ですが、、、お昼ごろに weekly-update のテンプレートファイルを作ってアップロードしますので、確認後、ひとまずここ ( #5 ) のコメント欄に練習として書いてみてもらってもよろしいでしょうか？

Githubでのmdファイルの記法は、 [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) というものです。ひとまず一読しておいてもらえると書き方がわかると思います。

テンプレートファイルはお昼ごろに作成し、出来次第リンクをここに載せますのでご確認ください。

**Comment by yorreb** [comment]
@takumi987 

お疲れ様です。昼休憩に入れましたので、今からまとめます。

あと、今朝の段階では分からなかったのですが、、、もしかして

> 自分もファイル編集が安全に行えるように@takumi987の中でいじって、慣れていきたいです。

というのは、

> ～行えるように https://github.com/Jmblllllr/core/tree/takumi987 の中でいじって、～

という意味でしょうか。。。？

もしそうでしたら、アップロード後にcloneをとって、そちらで編集後プルリクエストを送っていただく形でも大丈夫です。！

**Comment by yorreb** [comment]
@takumi987 

簡単ではありますが、、、weekly-update のテンプレートファイルです。

https://github.com/Jmblllllr/core/blob/master/weekly-update/2015-02-27.md

記法参考： [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/)

練習のつもりで書いてみてください。
