### ISSUE TITLE
hangout On Airミーティング以外での意思決定方法を設定

### ISSUE THREAD

**Issue by yorreb** [Jmblllllr/core#7]
@yorreb

取り決め時に毎回ハングアウトオンエアをやっていたのではスピード感があまりに無く手間であるため、その他の方法についても設定。

案出し後、オーガナイゼーションメンバーの合意ののち設定。

**Comment by yorreb** [comment]
設定していた2015.2.25のハングアウトミーティング https://github.com/Jmblllllr/core/blob/master/hangout-oa/etc/2015-02-25.md に、参加予定だったオーガナイゼーションメンバー2名のうち1名が諸事情により参加できないという事態に。当然何も決まらずに終了し、今後の動きも取れないという事態ですが、、、

今回の件については、
- ハングアウトミーティングに参加表明したのであれば、時間通りに参加できるように前持って準備する、準備できないのであればその旨を前もって連絡する。

という反省ももちろんなのですが、それよりもやはり、
- 現状の仕組みでは全体としての動きが遅すぎる

ということを強く感じました。

モチベーションが高まっている状態で動きを取れない仕組みは足枷以外の何物でもないのだなと痛感しています。

その上で、やはり方針の見直しが必要ではないかと。。

**Comment by yorreb** [comment]
付随する話だと思うので連投します。

『ではどのように方針を見直すのか』

と考えた時に、、、プロジェクトコンセプトがまだ曖昧なために、
方針の見直しについて明確な答えを見出せないという根本的な問題にぶつかりました。

プロジェクトコンセプトをしっかりまとめるところから始めませんか？

**Comment by takumi987** [comment]
まず、２月２５日（水）のミーティングについて謝罪致します。
メンバーの方には議論のために貴重な時間を割いていただいたのにも関わらず、私の不備で議論の機会を台無しにしてしまいました。申し訳ありませんでした。

21日にMTG内で話題に上がったJmblllllrのコンセプトがよりよいコミュニケーションの場となることに賛成します。そのため、Githubによって直接会って話さなくても議論できる体勢を整えていただいていることに感謝しております。しかし、ツールを正確に使いこなすには少し時間がかかると感じています。これは私の努力不足の問題なのですが、今現在の心境です。操作によってはまだ不明瞭な部分があり、またそれを習得するためのキャパが今の自分にあるのか不安であります。

システムとしてはクリアで強固なものであるという印象ですが、将来的にかちかちっとがんじがらめになってしまうように感じます。このシステムを整えていただいたことに対し恐縮です。

自分からの提案といて、LINE上で参加メンバーが案を出し、それについて賛否や提案し議論する方法です。話した内容は役割を持ったメンバーがLINEのノートにある一定期間（数週間分）の議論の要約を記載し、記録とする、など。

また、21日MTG内の内容のコンセプトに沿った意識をもって、日ごろのダンスでもコンセプトを意識したセッションや練習を行い、関わる人にもそれを感じてもらえるように働きかけていきたいと思います。

手を動かさず勝手なことを言って申し訳ありません。以上をコメントとさせていただきます。

**Comment by takumi987** [comment]
２番目のコメントについて気づくのが遅くなりました。すみません。

プロジェクトコンセプトのまとめるところから始めるということに賛成します。
どうまとめていくかの具体案は今パッと発言できないので発言の機会改めさせていただきたいと思います。

**Comment by yorreb** [comment]
@takumi987 

了解です。[プロジェクトコンセプトに関しては、昨夜、別にissuesを立てています(issues #1がその項目に該当すると判断し、名前を変更してコメント欄で少し話を進めています)ので、そちらを参照下さい。](https://github.com/Jmblllllr/core/issues/1)

サービスが難解という点は自分も少し感じています。これは昨夜のHangout On AirミーティングのFreeパートで話の流れから感じたことですが、、たしかにもっともっと簡単にコミットできるような形にしなければならないんだなと( [関連するブログ記事のリンク(雑感でありまとまっていませんが。。。)](https://yorreb.wordpress.com/2015/02/26/%e9%9b%91%e6%84%9f%e3%80%82/) )。

自分はこのサービスを以前から知っていたためにそのあたりの感覚(難解さ)が少し麻痺していたのかもしれませんね。。。配慮不足について謝罪します。

**Comment by yorreb** [comment]
@takumi987 

続けます。

まず、建設的な議論を行える提案をいただきありがとうございます。こういった意見の一つ一つが方針を見直すきっかけにもなりますし、プロジェクトの力になります。どんな些細なことでもいいのでこれからも気になる点があればどんどん意見してください。！

> 自分からの提案といて、LINE上で参加メンバーが案を出し、それについて賛否や提案し議論する方法です。話した内容は役割を持ったメンバーがLINEのノートにある一定期間（数週間分）の議論の要約を記載し、記録とする、など。

についてですが、ちょうど昨夜のミーティング時に同じ話をしていたのでそちらも参照していただければと思います。
- [Jmblllllrミーティング - February 25th 2015](https://plus.google.com/u/0/b/100887006868775331474/events/cei8mnjucrh071d24nte5vt73ps?hl=ja)

LINEを極力使いたくない理由は、「第三者がやりとりを見れない・口を出せないから」です。

そして、第三者がやりとりを見れる・口を出せるような形にしたい理由は、「そのほうが、閉鎖的なやり取りを内輪だけで続けるよりも反省の機会が増えて、より良いプロジェクトになりやすいから」です。

さらに続けます。が、仕事で手が空かないのでお昼ごろにかけたら書きます。。

**Comment by yorreb** [comment]
@takumi987 

続きです。

> 自分からの提案といて、LINE上で参加メンバーが案を出し、それについて賛否や提案し議論する方法です。話した内容は役割を持ったメンバーがLINEのノートにある一定期間（数週間分）の議論の要約を記載し、記録とする、など。

では例えば、LINEのように使う形で「雑談用のIssues掲示板」を作って、そのコメント欄でやり取りを行うのはどうでしょうか？

サンプルとして専用のissuesを立てています。 -> https://github.com/Jmblllllr/core/issues/10
